### ISSUE TITLE
Crash and exit R

### ISSUE THREAD

**Issue by timcdlucas** [ropensci/rfigshare#88]
Hi,

I'm just starting to play around with the package. I'm using R 3.1.2 in a terminal, rfigshare 0.3.6, sessionInfo [here](https://gist.github.com/timcdlucas/87086a5506e5b839732e)).

running
fs_search('ebola')

I get the following error and R crashes/quits

**\* Error in `/usr/lib/R/bin/exec/R': double free or corruption (fasttop): 0x000000000424c1f0 ***
Aborted (core dumped)

with fs_search('ebolas') R just hangs indefinitely.

Various other searches work fine so I don't know if it's something specific to the datasets in those searches?

**Comment by sckott** [comment]
looking at it...

**Comment by sckott** [comment]
weird, looks like `yaml::as.yaml()` is causing problems

At the end of the function `fs_search()` we convert each element found to `fs_object` class, which has a  print method 

```r
print.fs_object <- function(x, ...){
  cat(as.yaml(x))
}
```

And it's that `as.yaml()` calll that's causing a crash

At least one offending list is 

```r
$article_id
[1] 542740

$title
[1] "<p>Membrane deformations in response to integrin-ligand bonds.</p>"

$DOI
[1] "http://dx.doi.org/10.1371/journal.pcbi.1000604.g003"

$description
[1] "<p>The membrane surface is depicted in the presence of one, two, or three bonds with a rigid substrate (xy- and z- coordinates are not to scale); <i>\xc3<sub>s</sub></i>\n=\n1000 pN/nm, <i>l<sub>g</sub></i>\n=\n45 nm, <i>\xc3<sub>g</sub></i>\n=\n0.01 pN/nm. The inlays are the corresponding xy- contour maps of the z- membrane displacements. Note that larger areas of the membrane are brought in closer proximity to the ECM substrate when more bonds are placed in close proximity to each other.</p>"

$type
[1] "figure"

$defined_type
[1] "figure"

$url
[1] "http://api.figshare.com/v1/articles/542740"

$published_date
[1] "00:45, 11 Dec, 2009"

$modified_date
[1] "03:31, 21 Feb, 2013"

$authors
$authors[[1]]
        author_name 
"Matthew J. Paszek" 

$authors[[2]]
      author_name 
"David Boettiger" 

$authors[[3]]
        author_name 
"Valerie M. Weaver" 

$authors[[4]]
       author_name 
"Daniel A. Hammer" 


$links
list()
```

Which results in this when passed to `as.yaml()`

```r
R(14136,0x7fff7b2ff300) malloc: *** error for object 0x7f8e2ad67e00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

@cboettig thoughts?

a possibly related issue: https://github.com/viking/r-yaml/issues/12

**Comment by sckott** [comment]
on further exploration, looks like in that list above the `description` field is the offending part

```r
as.yaml(x$description)
``` 

```r
Error in as.yaml(x$description) :
  Emitter error: expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS
```

**Comment by sckott** [comment]
@cboettig @karthik unless you can think of a way to fix this, should we just parse the list manually to do the same thing `as.yaml()` does?

**Comment by cboettig** [comment]
@sckott Thanks for the detective work.  so does this seem like a bug we
should report for the yaml package?  Yeah, working around this manually is
probably a good idea, the yaml trick was more-or-less a quick hack for
pretty printing.

Tim, meanwhile if you simply assign the search results to an object rather
than printing them to the screen you should be able to avoid this error,
e.g.

hits <- fs_search("ebola")

you can also coerce the S3 class back into a normal list to avoid the print
method with the as.yaml being invoked:

class(hits) <- "list"

just a hack until we get the method fixed properly.  thanks for the bug
report.

**Comment by sckott** [comment]
@timcdlucas see what @cboettig said above

**Comment by sckott** [comment]
@cboettig yeah, i think we should report it there, I can do that. I can't see a way to dig in to the html string to see what could be causing the problem, but either way, it's probably something that should be fixed in the `yaml` package.

**Comment by karthik** [comment]
> unless you can think of a way to fix this, should we just parse the list manually to do the same thing as.yaml() does?

Yes please. Sounds like a good idea to implement a fix locally till we can get a bug fixed on `yaml`.

**Comment by timcdlucas** [comment]
Sorry only just saw this. Thanks @cboettig I'll give that a go when I get a moment.

**Comment by jcolomb** [comment]
I do not know if this is related but sounds similar: fs_browse make it crash. using this:
    hit=fs_browse(mine=TRUE)
    class(hit) <- "list"
    print(hit)

it crashes only after the last line, but still crashes...

**Comment by rvidal** [comment]
I can confirm. This still crashes. Did a very simple search like so:
`res <- fs_search("Boettiger", author = "Carl")`

If I attempt to print out `res` R/Rstudio just crash. Even if I do the class change to "list"
I can look at the structure but it won't print.

Has anyone managed to get this fixed?

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rfigshare_0.3.5.99

loaded via a namespace (and not attached):
 [1] colorspace_1.2-4 digest_0.6.4     ggplot2_1.0.0    grid_3.1.2       gtable_0.1.2    
 [6] httpuv_1.3.2     httr_0.3         MASS_7.3-35      munsell_0.4.2    plyr_1.8.1      
[11] proto_0.3-10     Rcpp_0.11.1      RCurl_1.95-4.3   reshape2_1.4     RJSONIO_1.3-0   
[16] scales_0.2.4     stringr_0.6.2    tools_3.1.2      XML_3.98-1.1     yaml_2.1.13
```

**Comment by cboettig** [comment]
rfigshare has been deprecated in favor of https://github.com/ropenscilabs/deposits
